# Generated by Django 2.0 on 2020-06-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
