# Generated by Django 2.0 on 2020-06-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_blog', '0005_auto_20200630_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default='1'),
        ),
    ]
