# Generated by Django 2.0 on 2020-07-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_blog', '0007_auto_20200702_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=140),
        ),
    ]
